// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocknote

import (
	context "context"

	id "github.com/pauloRohling/locknote/internal/domain/types/id"
	mock "github.com/stretchr/testify/mock"

	note "github.com/pauloRohling/locknote/internal/domain/note"

	pagination "github.com/pauloRohling/locknote/internal/domain/pagination"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// DeleteAllByUser provides a mock function with given fields: ctx, userId
func (_m *MockRepository) DeleteAllByUser(ctx context.Context, userId id.ID) error {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllByUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, id.ID) error); ok {
		r0 = rf(ctx, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteAllByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllByUser'
type MockRepository_DeleteAllByUser_Call struct {
	*mock.Call
}

// DeleteAllByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userId id.ID
func (_e *MockRepository_Expecter) DeleteAllByUser(ctx interface{}, userId interface{}) *MockRepository_DeleteAllByUser_Call {
	return &MockRepository_DeleteAllByUser_Call{Call: _e.mock.On("DeleteAllByUser", ctx, userId)}
}

func (_c *MockRepository_DeleteAllByUser_Call) Run(run func(ctx context.Context, userId id.ID)) *MockRepository_DeleteAllByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(id.ID))
	})
	return _c
}

func (_c *MockRepository_DeleteAllByUser_Call) Return(_a0 error) *MockRepository_DeleteAllByUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteAllByUser_Call) RunAndReturn(run func(context.Context, id.ID) error) *MockRepository_DeleteAllByUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteById provides a mock function with given fields: ctx, noteId
func (_m *MockRepository) DeleteById(ctx context.Context, noteId id.ID) error {
	ret := _m.Called(ctx, noteId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, id.ID) error); ok {
		r0 = rf(ctx, noteId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteById'
type MockRepository_DeleteById_Call struct {
	*mock.Call
}

// DeleteById is a helper method to define mock.On call
//   - ctx context.Context
//   - noteId id.ID
func (_e *MockRepository_Expecter) DeleteById(ctx interface{}, noteId interface{}) *MockRepository_DeleteById_Call {
	return &MockRepository_DeleteById_Call{Call: _e.mock.On("DeleteById", ctx, noteId)}
}

func (_c *MockRepository_DeleteById_Call) Run(run func(ctx context.Context, noteId id.ID)) *MockRepository_DeleteById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(id.ID))
	})
	return _c
}

func (_c *MockRepository_DeleteById_Call) Return(_a0 error) *MockRepository_DeleteById_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteById_Call) RunAndReturn(run func(context.Context, id.ID) error) *MockRepository_DeleteById_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, _a1
func (_m *MockRepository) FindAll(ctx context.Context, _a1 pagination.Pagination) ([]*note.Note, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*note.Note
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pagination.Pagination) ([]*note.Note, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pagination.Pagination) []*note.Note); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*note.Note)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pagination.Pagination) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 pagination.Pagination
func (_e *MockRepository_Expecter) FindAll(ctx interface{}, _a1 interface{}) *MockRepository_FindAll_Call {
	return &MockRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, _a1)}
}

func (_c *MockRepository_FindAll_Call) Run(run func(ctx context.Context, _a1 pagination.Pagination)) *MockRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pagination.Pagination))
	})
	return _c
}

func (_c *MockRepository_FindAll_Call) Return(_a0 []*note.Note, _a1 error) *MockRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindAll_Call) RunAndReturn(run func(context.Context, pagination.Pagination) ([]*note.Note, error)) *MockRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, _a1
func (_m *MockRepository) FindByID(ctx context.Context, _a1 id.ID) (*note.Note, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *note.Note
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, id.ID) (*note.Note, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, id.ID) *note.Note); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*note.Note)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, id.ID) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 id.ID
func (_e *MockRepository_Expecter) FindByID(ctx interface{}, _a1 interface{}) *MockRepository_FindByID_Call {
	return &MockRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, _a1)}
}

func (_c *MockRepository_FindByID_Call) Run(run func(ctx context.Context, _a1 id.ID)) *MockRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(id.ID))
	})
	return _c
}

func (_c *MockRepository_FindByID_Call) Return(_a0 *note.Note, _a1 error) *MockRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindByID_Call) RunAndReturn(run func(context.Context, id.ID) (*note.Note, error)) *MockRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, _a1
func (_m *MockRepository) Save(ctx context.Context, _a1 *note.Note) (*note.Note, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *note.Note
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *note.Note) (*note.Note, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *note.Note) *note.Note); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*note.Note)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *note.Note) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *note.Note
func (_e *MockRepository_Expecter) Save(ctx interface{}, _a1 interface{}) *MockRepository_Save_Call {
	return &MockRepository_Save_Call{Call: _e.mock.On("Save", ctx, _a1)}
}

func (_c *MockRepository_Save_Call) Run(run func(ctx context.Context, _a1 *note.Note)) *MockRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*note.Note))
	})
	return _c
}

func (_c *MockRepository_Save_Call) Return(_a0 *note.Note, _a1 error) *MockRepository_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Save_Call) RunAndReturn(run func(context.Context, *note.Note) (*note.Note, error)) *MockRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateById provides a mock function with given fields: ctx, _a1
func (_m *MockRepository) UpdateById(ctx context.Context, _a1 *note.Note) (*note.Note, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateById")
	}

	var r0 *note.Note
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *note.Note) (*note.Note, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *note.Note) *note.Note); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*note.Note)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *note.Note) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdateById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateById'
type MockRepository_UpdateById_Call struct {
	*mock.Call
}

// UpdateById is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *note.Note
func (_e *MockRepository_Expecter) UpdateById(ctx interface{}, _a1 interface{}) *MockRepository_UpdateById_Call {
	return &MockRepository_UpdateById_Call{Call: _e.mock.On("UpdateById", ctx, _a1)}
}

func (_c *MockRepository_UpdateById_Call) Run(run func(ctx context.Context, _a1 *note.Note)) *MockRepository_UpdateById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*note.Note))
	})
	return _c
}

func (_c *MockRepository_UpdateById_Call) Return(_a0 *note.Note, _a1 error) *MockRepository_UpdateById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpdateById_Call) RunAndReturn(run func(context.Context, *note.Note) (*note.Note, error)) *MockRepository_UpdateById_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
