// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: note_queries.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertNote = `-- name: InsertNote :one
INSERT INTO notes (id, title, content, created_at, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, content, created_at, created_by
`

type InsertNoteParams struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
	CreatedBy uuid.UUID `json:"createdBy"`
}

func (q *Queries) InsertNote(ctx context.Context, arg InsertNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, insertNote,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}
