// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: note_queries.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findNoteByID = `-- name: FindNoteByID :one
SELECT id, title, content, created_at, created_by
FROM notes
WHERE id = $1
  AND created_by = $2
`

type FindNoteByIDParams struct {
	ID        uuid.UUID `json:"id"`
	CreatedBy uuid.UUID `json:"createdBy"`
}

func (q *Queries) FindNoteByID(ctx context.Context, arg FindNoteByIDParams) (*Note, error) {
	row := q.db.QueryRow(ctx, findNoteByID, arg.ID, arg.CreatedBy)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return &i, err
}

const findNotesByUser = `-- name: FindNotesByUser :many
SELECT id, title, content, created_at, created_by
FROM notes
WHERE created_by = $1
ORDER BY $2
LIMIT $3
OFFSET $4
`

type FindNotesByUserParams struct {
	CreatedBy uuid.UUID   `json:"createdBy"`
	Column2   interface{} `json:"column2"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) FindNotesByUser(ctx context.Context, arg FindNotesByUserParams) ([]*Note, error) {
	rows, err := q.db.Query(ctx, findNotesByUser,
		arg.CreatedBy,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertNote = `-- name: InsertNote :one
INSERT INTO notes (id, title, content, created_at, created_by)
VALUES ($1, $2, $3, $4, $5) RETURNING id, title, content, created_at, created_by
`

type InsertNoteParams struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
	CreatedBy uuid.UUID `json:"createdBy"`
}

func (q *Queries) InsertNote(ctx context.Context, arg InsertNoteParams) (*Note, error) {
	row := q.db.QueryRow(ctx, insertNote,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return &i, err
}
